"""
BusinessObjectFactory (Phase 1 新建)
=====================================

业务对象工厂: 用于 BO CRUD 测试
"""
from typing import Dict, Any, List, Optional
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class BusinessObjectFactory(BaseFactory):
    """业务对象工厂 (BO)"""

    _OBJECT_TYPE = 'business_object'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'code': f'test_bo_{n}_{suffix}',
            'name': f'Test BO {n}',
            'description': f'Generated by BusinessObjectFactory #{n}',
            'product_id': None,  # 需配 ProductFactory
            'fields': [
                {'name': 'id', 'type': 'int', 'required': True},
                {'name': 'name', 'type': 'string', 'required': True},
            ],
            'status': 'draft',
        }

    @classmethod
    def create_published(cls, cookie=None, product_id: Optional[int] = None, **overrides) -> Dict[str, Any]:
        """创建已发布的 BO"""
        return cls.create(cookie=cookie, status='published', product_id=product_id, **overrides)

    @classmethod
    def create_with_product(cls, product_id: int, cookie=None, **overrides) -> Dict[str, Any]:
        """创建关联到指定 product 的 BO"""
        return cls.create(cookie=cookie, product_id=product_id, **overrides)
