"""
DomainFactory (Phase 1 新建)
=============================

域工厂: 用于多租户/域隔离测试
"""
from typing import Dict, Any, List
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class DomainFactory(BaseFactory):
    """域工厂 (多租户)"""

    _OBJECT_TYPE = 'domain'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'code': f'test_domain_{n}_{suffix}',
            'name': f'Test Domain {n}',
            'description': f'Generated by DomainFactory #{n}',
            'parent_id': None,
            'is_active': True,
        }

    @classmethod
    def create_child(cls, parent_id: int, cookie=None, **overrides) -> Dict[str, Any]:
        """创建子域"""
        return cls.create(cookie=cookie, parent_id=parent_id, **overrides)
