"""
EnumTypeFactory (P1-6a 新建)
==============================

枚举类型工厂: 用于枚举类型元数据的测试

yaml: meta/schemas/enum_type.yaml
表名: enum_types
required 字段:
- id (唯一业务键, immutable)
- name
- category (system/business)
- mutability (fullEditable/extensible/locked)
"""
from typing import Dict, Any
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class EnumTypeFactory(BaseFactory):
    """枚举类型工厂"""

    _OBJECT_TYPE = 'enum_type'

    # 标准 category
    CATEGORY_SYSTEM = 'system'
    CATEGORY_BUSINESS = 'business'

    # 标准 mutability
    MUT_FULL_EDITABLE = 'fullEditable'
    MUT_EXTENSIBLE = 'extensible'
    MUT_LOCKED = 'locked'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'id': f'test_enum_{n}_{suffix}',
            'name': f'Test Enum Type {n}',
            'category': cls.CATEGORY_BUSINESS,
            'mutability': cls.MUT_FULL_EDITABLE,
            'dimension_schema': None,
            'description': f'Generated by EnumTypeFactory #{n}',
            'is_active': True,
        }

    @classmethod
    def create_with_id(
        cls, type_id: str, name: str = None, cookie=None, **overrides
    ):
        """创建指定 id 的枚举类型"""
        if name is None:
            name = f'Enum {type_id}'
        return cls.create(cookie=cookie, id=type_id, name=name, **overrides)

    @classmethod
    def create_system_enum(
        cls, type_id: str, name: str = None, cookie=None, **overrides
    ):
        """创建系统枚举 (locked)"""
        return cls.create_with_id(
            type_id, name,
            cookie=cookie,
            category=cls.CATEGORY_SYSTEM,
            mutability=cls.MUT_LOCKED,
            **overrides
        )

    @classmethod
    def create_business_enum(
        cls, type_id: str, name: str = None, mutability: str = None,
        cookie=None, **overrides
    ):
        """创建业务枚举"""
        return cls.create_with_id(
            type_id, name,
            cookie=cookie,
            category=cls.CATEGORY_BUSINESS,
            mutability=mutability or cls.MUT_FULL_EDITABLE,
            **overrides
        )

    @classmethod
    def create_extensible(
        cls, type_id: str, name: str = None, cookie=None, **overrides
    ):
        """创建可扩展业务枚举"""
        return cls.create_business_enum(
            type_id, name,
            mutability=cls.MUT_EXTENSIBLE,
            cookie=cookie, **overrides
        )

    @classmethod
    def create_multi_dim(
        cls, type_id: str, dimension_schema: dict,
        name: str = None, cookie=None, **overrides
    ):
        """创建多维枚举"""
        import json as _json
        return cls.create_with_id(
            type_id, name,
            cookie=cookie,
            dimension_schema=_json.dumps(dimension_schema),
            **overrides
        )