"""
MenuPermissionFactory (P1-5c 新建)
===================================

菜单权限工厂: 用于菜单访问权限配置的测试

yaml: meta/schemas/menu_permission.yaml
表名: menu_permissions
required 字段:
- menu_code (唯一业务键, 不可修改)
- menu_name
- menu_path
"""
from typing import Dict, Any
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class MenuPermissionFactory(BaseFactory):
    """菜单权限工厂"""

    _OBJECT_TYPE = 'menu_permission'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'menu_code': f'test_menu_{n}_{suffix}',
            'menu_name': f'Test Menu {n}',
            'menu_path': f'/test/menu/{n}',
            'required_permissions': '[]',
            'required_any_permission': False,
            'parent_menu': None,
            'icon': 'menu',
            'display_order': n * 10,
            'is_visible': True,
            'description': f'Generated by MenuPermissionFactory #{n}',
        }

    @classmethod
    def create_with_code(
        cls, menu_code: str, menu_name: str, menu_path: str, cookie=None, **overrides
    ):
        """创建指定 menu_code 的菜单"""
        return cls.create(
            cookie=cookie,
            menu_code=menu_code, menu_name=menu_name, menu_path=menu_path,
            **overrides
        )

    @classmethod
    def create_with_required_permissions(
        cls, menu_code: str, menu_name: str, menu_path: str,
        required_permissions: list, any_permission: bool = False,
        cookie=None, **overrides
    ):
        """创建需要指定权限的菜单"""
        import json as _json
        return cls.create_with_code(
            menu_code, menu_name, menu_path,
            cookie=cookie,
            required_permissions=_json.dumps(required_permissions),
            required_any_permission=any_permission,
            **overrides
        )

    @classmethod
    def create_submenu(
        cls, parent_menu_code: str, menu_code: str,
        menu_name: str, menu_path: str, cookie=None, **overrides
    ):
        """创建子菜单"""
        return cls.create_with_code(
            menu_code, menu_name, menu_path,
            cookie=cookie,
            parent_menu=parent_menu_code,
            **overrides
        )

    @classmethod
    def create_hidden(cls, menu_code: str, menu_name: str, menu_path: str, cookie=None, **overrides):
        """创建隐藏菜单"""
        return cls.create_with_code(
            menu_code, menu_name, menu_path,
            cookie=cookie, is_visible=False, **overrides
        )