"""
MenuFactory (P1-6b 新建)
=========================

菜单工厂: 用于系统菜单配置的测试

yaml: meta/schemas/menu.yaml
表名: menus
required 字段:
- menu_code (唯一业务键)
- menu_name
- page_type (object_list/object_detail/...)
"""
from typing import Dict, Any
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class MenuFactory(BaseFactory):
    """菜单工厂"""

    _OBJECT_TYPE = 'menu'

    # 标准 page_type
    PAGE_OBJECT_LIST = 'object_list'
    PAGE_OBJECT_DETAIL = 'object_detail'
    PAGE_DASHBOARD = 'dashboard'
    PAGE_CUSTOM = 'custom'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'menu_code': f'test_menu_{n}_{suffix}',
            'menu_name': f'Test Menu {n}',
            'menu_path': f'/test/menu/{n}',
            'page_type': cls.PAGE_OBJECT_LIST,
            'parent_menu_code': None,
            'icon': 'menu',
            'display_order': n * 10,
            'is_visible': True,
            'bo_bindings': '[]',
            'required_permissions': '[]',
            'description': f'Generated by MenuFactory #{n}',
        }

    @classmethod
    def create_with_code(
        cls, menu_code: str, menu_name: str, page_type: str = None,
        cookie=None, **overrides
    ):
        """创建指定 menu_code 的菜单"""
        return cls.create(
            cookie=cookie,
            menu_code=menu_code, menu_name=menu_name,
            page_type=page_type or cls.PAGE_OBJECT_LIST, **overrides
        )

    @classmethod
    def create_list_page(
        cls, menu_code: str, menu_name: str, object_type: str,
        menu_path: str = None, cookie=None, **overrides
    ):
        """创建对象列表页菜单"""
        import json as _json
        if menu_path is None:
            menu_path = f'/{object_type}-management'
        return cls.create_with_code(
            menu_code, menu_name,
            page_type=cls.PAGE_OBJECT_LIST,
            cookie=cookie,
            menu_path=menu_path,
            bo_bindings=_json.dumps([{'object_type': object_type}]),
            **overrides
        )

    @classmethod
    def create_detail_page(
        cls, menu_code: str, menu_name: str, object_type: str,
        menu_path: str = None, cookie=None, **overrides
    ):
        """创建对象详情页菜单"""
        import json as _json
        if menu_path is None:
            menu_path = f'/detail/{object_type}/{object_type}-detail'
        return cls.create_with_code(
            menu_code, menu_name,
            page_type=cls.PAGE_OBJECT_DETAIL,
            cookie=cookie,
            menu_path=menu_path,
            bo_bindings=_json.dumps([{'object_type': object_type}]),
            **overrides
        )

    @classmethod
    def create_submenu(
        cls, parent_menu_code: str, menu_code: str,
        menu_name: str, cookie=None, **overrides
    ):
        """创建子菜单"""
        return cls.create_with_code(
            menu_code, menu_name,
            cookie=cookie, parent_menu_code=parent_menu_code, **overrides
        )

    @classmethod
    def create_hidden(cls, menu_code: str, menu_name: str, cookie=None, **overrides):
        """创建隐藏菜单"""
        return cls.create_with_code(
            menu_code, menu_name,
            cookie=cookie, is_visible=False, **overrides
        )