"""
UserGroupFactory (Phase 1 新建)
================================

用户组工厂: 用于权限/订阅测试
"""
from typing import Dict, Any, List, Optional
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class UserGroupFactory(BaseFactory):
    """用户组工厂"""

    _OBJECT_TYPE = 'user_group'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'code': f'test_group_{n}_{suffix}',
            'name': f'Test Group {n}',
            'description': f'Generated by UserGroupFactory #{n}',
            'member_ids': [],
        }

    @classmethod
    def create_with_members(cls, member_ids: List[int], cookie=None, **overrides) -> Dict[str, Any]:
        """创建带成员的用户组"""
        return cls.create(cookie=cookie, member_ids=member_ids, **overrides)
