"""
PermissionFactory (Phase 4 新建)
==================================

权限工厂: 用于 ACL / RBAC 测试
"""
from typing import Dict, Any, List
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class PermissionFactory(BaseFactory):
    """权限工厂"""

    _OBJECT_TYPE = 'permission'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'code': f'test_perm_{n}_{suffix}',
            'name': f'Test Permission {n}',
            'description': f'Generated by PermissionFactory #{n}',
            'resource': 'business_object',
            'action': 'read',
        }

    @classmethod
    def create_read(cls, resource: str, cookie=None, **overrides) -> Dict[str, Any]:
        """创建读权限"""
        return cls.create(cookie=cookie, resource=resource, action='read', **overrides)

    @classmethod
    def create_write(cls, resource: str, cookie=None, **overrides) -> Dict[str, Any]:
        """创建写权限"""
        return cls.create(cookie=cookie, resource=resource, action='write', **overrides)

    @classmethod
    def create_admin(cls, cookie=None, **overrides) -> Dict[str, Any]:
        """创建管理员权限 (*:*)"""
        return cls.create(cookie=cookie, resource='*', action='*', **overrides)
