"""
PermissionBundleFactory (Phase 6 新建)
=========================================

权限包工厂: 用于预定义权限组合包测试

yaml: meta/schemas/permission_bundle.yaml
required 字段:
- bundle_code (唯一编码, 不可修改)
- bundle_name (显示名称)
"""
from typing import Dict, Any
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class PermissionBundleFactory(BaseFactory):
    """权限包工厂"""

    _OBJECT_TYPE = 'permission_bundle'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'bundle_code': f'test_bundle_{n}_{suffix}',
            'bundle_name': f'Test Bundle {n}',
            'description': f'Generated by PermissionBundleFactory #{n}',
            'menu_permissions': '[]',
            'function_permissions': '[]',
            'data_permission_template': '{}',
            'is_active': True,
            'is_system': False,
        }

    @classmethod
    def create_with_permissions(
        cls, bundle_code: str, bundle_name: str,
        function_permissions: list = None, menu_permissions: list = None,
        cookie=None, **overrides
    ) -> Dict[str, Any]:
        """创建包含指定权限的权限包"""
        import json
        return cls.create(
            cookie=cookie,
            bundle_code=bundle_code,
            bundle_name=bundle_name,
            function_permissions=json.dumps(function_permissions or []),
            menu_permissions=json.dumps(menu_permissions or []),
            **overrides
        )

    @classmethod
    def create_readonly_bundle(cls, cookie=None, **overrides) -> Dict[str, Any]:
        """创建只读权限包"""
        n = cls._next_counter()
        suffix = unique_str(4)
        return cls.create(
            cookie=cookie,
            bundle_code=f'readonly_{n}_{suffix}',
            bundle_name=f'Read Only Bundle {n}',
            function_permissions='["*:read"]',
            **overrides
        )
