"""
ProductFactory (Phase 4 新建)
==============================

产品工厂: 用于产品/应用域测试
"""
from typing import Dict, Any
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class ProductFactory(BaseFactory):
    """产品工厂"""

    _OBJECT_TYPE = 'product'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'code': f'test_product_{n}_{suffix}',
            'name': f'Test Product {n}',
            'description': f'Generated by ProductFactory #{n}',
            'is_active': True,
            'config': {'theme': 'default', 'features': ['basic']},
        }

    @classmethod
    def create_premium(cls, cookie=None, **overrides) -> Dict[str, Any]:
        """创建 premium 产品"""
        return cls.create(
            cookie=cookie,
            config={'theme': 'premium', 'features': ['basic', 'advanced', 'analytics']},
            **overrides
        )
