"""
RoleFactory (Phase 1 新建)
=========================

角色工厂: 解决硬编码权限码
"""
from typing import Dict, Any, List
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class RoleFactory(BaseFactory):
    """角色工厂"""

    _OBJECT_TYPE = 'role'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'code': f'test_role_{n}_{suffix}',
            'name': f'Test Role {n}',
            'description': f'Generated by RoleFactory #{n}',
            'permissions': ['user:read', 'user:list'],
        }

    @classmethod
    def create_admin_role(cls, cookie=None, **overrides) -> Dict[str, Any]:
        """创建 admin 角色 (含 * 权限)"""
        return cls.create(
            cookie=cookie,
            code=f'admin_{unique_str(8)}',
            name='Admin',
            description='Full admin role',
            permissions=['*'],
            **overrides
        )

    @classmethod
    def create_readonly_role(cls, cookie=None, **overrides) -> Dict[str, Any]:
        """创建只读角色"""
        return cls.create(
            cookie=cookie,
            permissions=['*:read'],
            **overrides
        )
