"""
ScheduledTaskFactory (P1-5a 新建)
==================================

任务定义工厂: 用于后台调度任务配置的测试

yaml: meta/schemas/scheduled_task.yaml
表名: scheduled_tasks
required 字段:
- code (唯一业务键)
- name
"""
from typing import Dict, Any
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class ScheduledTaskFactory(BaseFactory):
    """任务定义工厂"""

    _OBJECT_TYPE = 'scheduled_task'

    # 标准 trigger_type
    TRIGGER_CRON = 'cron'
    TRIGGER_EVENT = 'event'
    TRIGGER_WEBHOOK = 'webhook'
    TRIGGER_MANUAL = 'manual'
    TRIGGER_INTERVAL = 'interval'

    # 标准 status
    STATUS_ACTIVE = 'active'
    STATUS_PAUSED = 'paused'
    STATUS_DISABLED = 'disabled'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'code': f'test_task_{n}_{suffix}',
            'name': f'Test Scheduled Task {n}',
            'description': f'Generated by ScheduledTaskFactory #{n}',
            'category': 'test',
            'trigger_type': cls.TRIGGER_CRON,
            'cron_expression': '0 * * * *',
            'interval_seconds': None,
            'handler': 'meta.handlers.test_handler',
            'enabled': True,
            'status': cls.STATUS_ACTIVE,
            'retry_policy': '{}',
            'timeout_seconds': 300,
        }

    @classmethod
    def create_with_code(
        cls, code: str, name: str = None, cookie=None, **overrides
    ):
        """创建指定 code 的任务"""
        if name is None:
            name = f'Task {code}'
        return cls.create(cookie=cookie, code=code, name=name, **overrides)

    @classmethod
    def create_cron_task(
        cls, code: str, cron: str, name: str = None, cookie=None, **overrides
    ):
        """创建 cron 定时任务"""
        return cls.create_with_code(
            code, name,
            cookie=cookie,
            trigger_type=cls.TRIGGER_CRON,
            cron_expression=cron,
            **overrides
        )

    @classmethod
    def create_event_task(cls, code: str, name: str = None, cookie=None, **overrides):
        """创建事件驱动任务"""
        return cls.create_with_code(
            code, name,
            cookie=cookie,
            trigger_type=cls.TRIGGER_EVENT,
            cron_expression=None,
            **overrides
        )

    @classmethod
    def create_webhook_task(cls, code: str, name: str = None, cookie=None, **overrides):
        """创建 Webhook 任务"""
        return cls.create_with_code(
            code, name,
            cookie=cookie,
            trigger_type=cls.TRIGGER_WEBHOOK,
            **overrides
        )

    @classmethod
    def create_disabled(cls, code: str, name: str = None, cookie=None, **overrides):
        """创建已禁用的任务"""
        return cls.create_with_code(
            code, name,
            cookie=cookie,
            enabled=False, status=cls.STATUS_DISABLED, **overrides
        )

    @classmethod
    def create_interval_task(
        cls, code: str, interval_seconds: int, name: str = None, cookie=None, **overrides
    ):
        """创建 interval 定时任务"""
        return cls.create_with_code(
            code, name,
            cookie=cookie,
            trigger_type=cls.TRIGGER_INTERVAL,
            cron_expression=None,
            interval_seconds=interval_seconds,
            **overrides
        )