"""
VersionFactory (Phase 1 新建)
==============================

版本工厂: 用于版本管理测试
"""
from typing import Dict, Any, Optional
from ._base import BaseFactory, unique_str, register_factory


@register_factory
class VersionFactory(BaseFactory):
    """版本工厂"""

    _OBJECT_TYPE = 'version'

    @classmethod
    def _base_defaults(cls) -> Dict[str, Any]:
        n = cls._next_counter()
        suffix = unique_str(4)
        return {
            'version': f'1.0.{n}',
            'name': f'Test Version {n}',
            'description': f'Generated by VersionFactory #{n}',
            'bo_id': None,  # 需配 BusinessObjectFactory
            'status': 'draft',
            'schema': {},
        }

    @classmethod
    def create_released(cls, bo_id: int, cookie=None, **overrides) -> Dict[str, Any]:
        """创建已发布版本"""
        return cls.create(cookie=cookie, bo_id=bo_id, status='released', **overrides)

    @classmethod
    def create_for_bo(cls, bo_id: int, cookie=None, **overrides) -> Dict[str, Any]:
        """为指定 BO 创建版本"""
        return cls.create(cookie=cookie, bo_id=bo_id, **overrides)
