"""
Auto-generated E2E test from recording: D:\filework\excel-to-diagram\test_helpers\scripts\..\test_output\verify_recording.json

Recorded at: 2026-06-02T07:10:36.256115+00:00
Events: 2
Duration: 30740ms

Generated by CodeGenerator on 2026-06-02T15:10:39.307946
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'test_helpers'))
from browser_auth_cli import PlaywrightCLI


def test_verify_generated():
    """
    Recorded test: verify_generated
    Auto-generated from manual E2E session.
    """
    cli = PlaywrightCLI(headless=True)

    try:
        # Navigate to /
        cli.authenticated_navigate('/')

        # Step 1: click Self Updated Name
        cli.click("span.user-menu__name", wait_after=500)

        # Verify no errors
        health = cli.check_health()
        assert health['healthy'], f"Page unhealthy: {health['summary']}"

        print("[PASS] verify_generated")
        return True

    except Exception as e:
        print(f"[FAIL] verify_generated: {e}")
        cli.screenshot("test_output/verify_generated_failure.png")
        return False

    finally:
        cli.close()


if __name__ == "__main__":
    success = test_verify_generated()
    sys.exit(0 if success else 1)
