// Auto-generated by scripts/generate_action_types.js
// DO NOT EDIT MANUALLY
// Date: 2026-06-06T00:49:36.919Z

export type ActionId = 'audit.export'
  | 'audit.retry'
  | 'batch_delete'
  | 'batch_save'
  | 'enum_type.create'
  | 'enum_type.delete'
  | 'enum_type.update'
  | 'function.aggregate.query'
  | 'function.aggregate.refresh'
  | 'function.subscription.list'
  | 'function.value_help.resolve'
  | 'subscription.create'
  | 'user.authenticate'
  | 'user.change_password'
  | 'user.get_current'
  | 'user.logout'
  | 'user.reset_password'
  | 'user.update_profile'
  | 'version.clear_other_current';

export interface ActionRegistry {
  'audit.export': { input: {
  action?: string;
  end_date?: string;
  format?: 'xlsx' | 'csv';
  object_type?: string;
  start_date?: string;
  user_name?: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'audit.retry': { input: {
  record_id: number;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'batch_delete': { input: {
  force?: boolean;
  ids: number[];
  object_type: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'batch_save': { input: {
  drafts: {
  fields?: any;
  is_new?: boolean;
  row_id?: any;
}[];
  object_type: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'enum_type.create': { input: {
  category?: 'business';
  description?: string;
  dimension_schema?: any;
  id: string;
  mutability?: 'extensible' | 'frozen';
  name: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'enum_type.delete': { input: {
  id: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'enum_type.update': { input: {
  description?: string;
  dimension_schema?: any;
  id: string;
  mutability?: 'extensible' | 'frozen';
  name?: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'function.aggregate.query': { input: {
  aggregate_id: string;
  filters?: any;
  limit?: number;
  order_by?: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'function.aggregate.refresh': { input: {
  aggregate_id: string;
  force?: boolean;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'function.subscription.list': { input: {
  object_type?: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'function.value_help.resolve': { input: {
  code_field?: string;
  display_field?: string;
  source_id: string;
  source_type: 'enum' | 'bo' | 'custom';
  value: any;
  value_field?: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'subscription.create': { input: {
  channel?: 'websocket' | 'webhook';
  event_types?: 'created' | 'updated' | 'deleted'[];
  filter_condition?: any;
  object_type: string;
  webhook_secret?: string;
  webhook_url?: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'user.authenticate': { input: {
  password: string;
  username: string;
}; output: {
  token?: string;
  user?: any;
}; };
  'user.change_password': { input: {
  new_password: string;
  old_password: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'user.get_current': { input: any; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'user.logout': { input: any; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'user.reset_password': { input: {
  new_password: string;
  user_id: number;
}; output: {
  must_change_password?: boolean;
  user_id?: number;
}; };
  'user.update_profile': { input: {
  date_style?: string;
  display_name?: string;
  email?: string;
  hour_cycle?: string;
  locale?: string;
  time_style?: string;
  timezone?: string;
}; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
  'version.clear_other_current': { input: any; output: {
  data?: any;
  message?: string;
  success?: boolean;
}; };
}

export interface BoActionResponse<T = any> {
  success: boolean;
  data: T;
  message: string;
}

export declare function callPost<T extends ActionId>(
  action_id: T,
  params: ActionRegistry[T]['input']
): Promise<BoActionResponse<ActionRegistry[T]['output']>>;

export declare function callGet<T extends ActionId>(
  action_id: T,
  params?: ActionRegistry[T]['input']
): Promise<BoActionResponse<ActionRegistry[T]['output']>>;

export declare function callPut<T extends ActionId>(
  action_id: T,
  params: ActionRegistry[T]['input']
): Promise<BoActionResponse<ActionRegistry[T]['output']>>;

export declare function callDelete<T extends ActionId>(
  action_id: T,
  params: ActionRegistry[T]['input']
): Promise<BoActionResponse<ActionRegistry[T]['output']>>;

export const ACTIONS = [
  { id: 'audit.export', summary: "导出审计日志为 xlsx/csv 文件（管理员, [DECORATIVE] v3.1 文件流）", method: 'POST', requiresAdmin: true },
  { id: 'audit.retry', summary: "重试失败的审计日志记录（管理员）", method: 'POST', requiresAdmin: true },
  { id: 'batch_delete', summary: "批量删除（任意 object_type, 与 batch_save 对称）", method: 'POST', requiresAdmin: false },
  { id: 'batch_save', summary: "草稿批量保存（支持 is_new/create+update）", method: 'POST', requiresAdmin: false },
  { id: 'enum_type.create', summary: "创建业务枚举类型 (admin 限定, 不允许 system 类别)", method: 'POST', requiresAdmin: true },
  { id: 'enum_type.delete', summary: "删除业务枚举类型 (admin 限定, 仅当无 enum_values 时)", method: 'POST', requiresAdmin: true },
  { id: 'enum_type.update', summary: "更新业务枚举类型 (admin 限定, system 不可改)", method: 'POST', requiresAdmin: true },
  { id: 'function.aggregate.query', summary: "[FUNCTION] [Function] 查询聚合表数据", method: 'GET', requiresAdmin: false },
  { id: 'function.aggregate.refresh', summary: "[FUNCTION] [Function] 刷新聚合表 (admin 限定, 注意: 实际是写操作, 标为 function 仅因 aggregate 域)", method: 'GET', requiresAdmin: true },
  { id: 'function.subscription.list', summary: "[FUNCTION] [Function] 列出当前用户的订阅 (可选 object_type 过滤)", method: 'GET', requiresAdmin: false },
  { id: 'function.value_help.resolve', summary: "[FUNCTION] [Function] 解析 value_help 值的显示信息 (display/code)", method: 'GET', requiresAdmin: false },
  { id: 'subscription.create', summary: "创建对象变更通知订阅（websocket/webhook）", method: 'POST', requiresAdmin: false },
  { id: 'user.authenticate', summary: "用户登录认证", method: 'POST', requiresAdmin: false },
  { id: 'user.change_password', summary: "修改当前用户密码", method: 'POST', requiresAdmin: false },
  { id: 'user.get_current', summary: "获取当前登录用户信息", method: 'POST', requiresAdmin: false },
  { id: 'user.logout', summary: "用户登出（token 加入黑名单）", method: 'POST', requiresAdmin: false },
  { id: 'user.reset_password', summary: "管理员重置指定用户密码（强制 must_change_password=1）", method: 'POST', requiresAdmin: true },
  { id: 'user.update_profile', summary: "更新当前用户个人信息（display_name/email/locale/timezone 等）", method: 'POST', requiresAdmin: false },
  { id: 'version.clear_other_current', summary: "清除同产品下其他版本的 is_current 标志 (set_current action 的 trigger)", method: 'POST', requiresAdmin: false },
] as const;
