import sqlite3
conn = sqlite3.connect(r'meta\architecture.db')
conn.row_factory = sqlite3.Row
cur = conn.cursor()

cur.execute("SELECT * FROM data_permissions WHERE user_id = 1223")
for r in cur.fetchall():
    print('data_permissions entry:')
    print(dict(r))

# Also check if data_permission_interceptor logs show anything
# Let's see what SQL would be generated by query_builder
print()
cur.execute("PRAGMA table_info(data_permissions)")
for c in cur.fetchall():
    print(f'  {dict(c)}')
