#!/usr/bin/env pwsh
# ============================================================================
# Agent Bootstrap Script v1.0 (2026-06-19)
# ============================================================================
# 创建独立的 git worktree + 分配独立端口 + 创建 .env.agent
# 解决多 agent 并行开发时"测试哪个版本"的问题
#
# 用法:
#   powershell -File scripts/agent_bootstrap.ps1 -AgentName <name> -Port <3011-3019>
#
# 示例:
#   powershell -File scripts/agent_bootstrap.ps1 -AgentName agent-A -Port 3011
#
# 端口分配规则:
#   3010 = main (生产 / 用户访问)
#   3011-3019 = agent 工作区 (每个 agent 独立)
# ============================================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$AgentName,

    [Parameter(Mandatory=$true)]
    [int]$Port,

    [string]$BaseBranch = "main"
)

# ===== 强制铁律 echo =====
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  AGENT BOOTSTRAP v1.0 - 你必须遵守的 5 条铁律" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  L1: 不要在主工作树 commit (用 worktree)" -ForegroundColor Yellow
Write-Host "  L2: 不要在主工作树 stash" -ForegroundColor Yellow
Write-Host "  L3: 不要碰 stash@{0}" -ForegroundColor Yellow
Write-Host "  L4: commit 前必看 .agent-status.json" -ForegroundColor Yellow
Write-Host "  L5: 服务跑在主工作树, 测试用你的端口 (-Port)" -ForegroundColor Yellow
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# ===== 参数验证 =====
if ($Port -lt 3011 -or $Port -gt 3019) {
    Write-Host "❌ 端口必须在 3011-3019 范围内 (main = 3010)" -ForegroundColor Red
    exit 1
}

if ($AgentName -match '[^a-zA-Z0-9_-]') {
    Write-Host "❌ AgentName 只能含字母数字下划线" -ForegroundColor Red
    exit 1
}

# ===== 路径计算 =====
$repoRoot = git rev-parse --show-toplevel
$repoRoot = $repoRoot.Trim()
$parentDir = Split-Path -Parent $repoRoot
$worktreePath = Join-Path $parentDir "${AgentName}-worktree"
$branchName = "$AgentName-$BaseBranch"

Set-Location $repoRoot

# ===== 检查 main 工作树状态 =====
Write-Host "[1/6] 检查主工作树状态..." -ForegroundColor Cyan
$mainStatus = git status --porcelain 2>&1
if ($mainStatus) {
    Write-Host "⚠️ 主工作树有未提交修改:" -ForegroundColor Yellow
    Write-Host $mainStatus
    Write-Host ""
    $confirm = Read-Host "是否继续？ (y/N)"
    if ($confirm -ne 'y') {
        Write-Host "❌ 已取消" -ForegroundColor Red
        exit 1
    }
}

# ===== 创建 worktree =====
Write-Host "[2/6] 创建 worktree: $worktreePath (分支: $branchName, 端口: $Port)" -ForegroundColor Cyan
$worktreeResult = git worktree add -b $branchName $worktreePath $BaseBranch 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Worktree 创建失败:" -ForegroundColor Red
    Write-Host $worktreeResult
    exit 1
}

Set-Location $worktreePath

# ===== 创建 .env.agent =====
Write-Host "[3/6] 创建 .env.agent (端口配置)" -ForegroundColor Cyan
$envContent = @"
# Generated by agent_bootstrap.ps1 v1.0 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
AGENT_NAME=$AgentName
AGENT_PORT=$Port
AGENT_WORKTREE=$worktreePath
AGENT_BRANCH=$branchName
AGENT_BASE_BRANCH=$BaseBranch
AGENT_IN_WORKTREE=1

# 前端端口 (3004 + offset)
VITE_PORT=$((3004 + ($Port - 3010)))
"@
$envPath = Join-Path $worktreePath ".env.agent"
Set-Content -Path $envPath -Value $envContent -Encoding UTF8

# ===== 注册端口 =====
Write-Host "[4/6] 注册端口到 .coord/ports.json" -ForegroundColor Cyan
$coordDir = Join-Path $parentDir ".coord"
$portsFile = Join-Path $coordDir "ports.json"

if (-not (Test-Path $coordDir)) {
    New-Item -ItemType Directory -Path $coordDir -Force | Out-Null
}

if (Test-Path $portsFile) {
    $ports = Get-Content $portsFile -Raw | ConvertFrom-Json
} else {
    $ports = @{
        allocated = @{}
        reserved = @{
            "3010" = @{ owner = "main"; role = "production"; status = "running" }
        }
    }
}

# 检查端口冲突
$portStr = $Port.ToString()
if ($ports.allocated.$portStr -or $ports.reserved.$portStr) {
    Write-Host "❌ 端口 $Port 已被占用" -ForegroundColor Red
    Write-Host "请用 -Port 选择其他端口 (3011-3019)" -ForegroundColor Red
    exit 1
}

$ports.allocated.$portStr = @{
    owner = $AgentName
    role = "agent-worktree"
    status = "active"
    worktree = $worktreePath
    branch = $branchName
    allocated_at = (Get-Date -Format "o")
}

$ports | ConvertTo-Json -Depth 5 | Set-Content -Path $portsFile -Encoding UTF8

# ===== 安装依赖 =====
Write-Host "[5/6] 安装依赖 (跳过, 请手动 npm install)" -ForegroundColor Cyan
Write-Host "  cd $worktreePath" -ForegroundColor Gray
Write-Host "  npm install" -ForegroundColor Gray

# ===== 创建 AGENT_GUIDELINES.md (如果不存在) =====
$guidelinesPath = Join-Path $parentDir "AGENT_GUIDELINES.md"
if (-not (Test-Path $guidelinesPath)) {
    Write-Host "  ⚠️ AGENT_GUIDELINES.md 不存在, 请创建" -ForegroundColor Yellow
}

# ===== 完成 =====
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  ✅ AGENT BOOTSTRAP 完成" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Agent 名称: $AgentName" -ForegroundColor White
Write-Host "  Worktree:   $worktreePath" -ForegroundColor White
Write-Host "  分支:       $branchName" -ForegroundColor White
Write-Host "  后端端口:   $Port" -ForegroundColor White
Write-Host "  前端端口:   $((3004 + ($Port - 3010)))" -ForegroundColor White
Write-Host "  端口注册:   .coord/ports.json" -ForegroundColor White
Write-Host "  Env 文件:   $worktreePath\.env.agent" -ForegroundColor White
Write-Host ""
Write-Host "  下一步:" -ForegroundColor Cyan
Write-Host "    cd $worktreePath" -ForegroundColor White
Write-Host "    npm install" -ForegroundColor White
Write-Host "    cp d:\filework\spec_template.md .\spec.md  # 写任务规格" -ForegroundColor White
Write-Host "    # 然后开始开发" -ForegroundColor White
Write-Host ""
Write-Host "  测试时:" -ForegroundColor Cyan
Write-Host "    python test.py --port $Port --single <test_path>" -ForegroundColor White
Write-Host "    浏览器: http://localhost:$((3004 + ($Port - 3010)))/" -ForegroundColor White
Write-Host ""
Write-Host "  完成后:" -ForegroundColor Cyan
Write-Host "    cd $worktreePath" -ForegroundColor White
Write-Host "    git add . && git commit -m '...'" -ForegroundColor White
Write-Host "    # 通知协调者 merge" -ForegroundColor White
Write-Host ""