#!/usr/bin/env pwsh
# ============================================================================
# Agent Bootstrap Script v1.0 (2026-06-19)
# ============================================================================
#  git worktree +  +  .env.agent
#  agent ""
#
# :
#   powershell -File scripts/agent_bootstrap.ps1 -AgentName <name> -Port <3011-3019>
#
# :
#   powershell -File scripts/agent_bootstrap.ps1 -AgentName agent-A -Port 3011
#
# :
#   3010 = main ( / )
#   3011-3019 = agent  ( agent )
# ============================================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$AgentName,

    [Parameter(Mandatory=$true)]
    [int]$Port,

    [string]$BaseBranch = "main"
)

# =====  echo =====
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  AGENT BOOTSTRAP v1.0 -  5 " -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  L1:  commit ( worktree)" -ForegroundColor Yellow
Write-Host "  L2:  stash" -ForegroundColor Yellow
Write-Host "  L3:  stash@{0}" -ForegroundColor Yellow
Write-Host "  L4: commit  .agent-status.json" -ForegroundColor Yellow
Write-Host "  L5: ,  (-Port)" -ForegroundColor Yellow
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# =====  =====
if ($Port -lt 3011 -or $Port -gt 3019) {
    Write-Host "[ERROR]  3011-3019  (main = 3010)" -ForegroundColor Red
    exit 1
}

if ($AgentName -match '[^a-zA-Z0-9_-]') {
    Write-Host "[ERROR] AgentName " -ForegroundColor Red
    exit 1
}

# =====  =====
$repoRoot = git rev-parse --show-toplevel
$repoRoot = $repoRoot.Trim()
$parentDir = Split-Path -Parent $repoRoot
$worktreePath = Join-Path $parentDir "${AgentName}-worktree"
$branchName = "$AgentName-$BaseBranch"

Set-Location $repoRoot

# =====  main  =====
Write-Host "[1/6] ..." -ForegroundColor Cyan
$mainStatus = git status --porcelain 2>&1
if ($mainStatus) {
    Write-Host "[WARN] :" -ForegroundColor Yellow
    Write-Host $mainStatus
    Write-Host ""
    $confirm = Read-Host "? (y/N)"
    if ($confirm -ne 'y') {
        Write-Host "[ERROR] " -ForegroundColor Red
        exit 1
    }
}

# =====  worktree =====
Write-Host "[2/6]  worktree: $worktreePath (: $branchName, : $Port)" -ForegroundColor Cyan
$worktreeResult = git worktree add -b $branchName $worktreePath $BaseBranch 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Worktree :" -ForegroundColor Red
    Write-Host $worktreeResult
    exit 1
}

Set-Location $worktreePath

# =====  .env.agent =====
Write-Host "[3/6]  .env.agent ()" -ForegroundColor Cyan
$envContent = @"
# Generated by agent_bootstrap.ps1 v1.0 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
AGENT_NAME=$AgentName
AGENT_PORT=$Port
AGENT_WORKTREE=$worktreePath
AGENT_BRANCH=$branchName
AGENT_BASE_BRANCH=$BaseBranch
AGENT_IN_WORKTREE=1

#  (3004 + offset)
VITE_PORT=$((3004 + ($Port - 3010)))
"@
$envPath = Join-Path $worktreePath ".env.agent"
Set-Content -Path $envPath -Value $envContent -Encoding UTF8

# =====  =====
Write-Host "[4/6]  .coord/ports.json" -ForegroundColor Cyan
$coordDir = Join-Path $parentDir ".coord"
$portsFile = Join-Path $coordDir "ports.json"

if (-not (Test-Path $coordDir)) {
    New-Item -ItemType Directory -Path $coordDir -Force | Out-Null
}

if (Test-Path $portsFile) {
    # Convert from JSON (PSCustomObject -> Hashtable via @())
    $jsonContent = Get-Content $portsFile -Raw | ConvertFrom-Json
    $ports = @{
        allocated = @{}
        reserved = @{}
    }
    if ($jsonContent.allocated) {
        foreach ($key in $jsonContent.allocated.PSObject.Properties) {
            $ports.allocated[$key.Name] = @{
                owner = $key.Value.owner
                role = $key.Value.role
                status = $key.Value.status
            }
            if ($key.Value.worktree) { $ports.allocated[$key.Name].worktree = $key.Value.worktree }
            if ($key.Value.branch) { $ports.allocated[$key.Name].branch = $key.Value.branch }
            if ($key.Value.allocated_at) { $ports.allocated[$key.Name].allocated_at = $key.Value.allocated_at }
        }
    }
    if ($jsonContent.reserved) {
        foreach ($key in $jsonContent.reserved.PSObject.Properties) {
            $ports.reserved[$key.Name] = @{
                owner = $key.Value.owner
                role = $key.Value.role
                status = $key.Value.status
            }
        }
    }
} else {
    $ports = @{
        allocated = @{}
        reserved = @{
            "3010" = @{ owner = "main"; role = "production"; status = "running" }
        }
    }
}

# 
$portStr = $Port.ToString()
if ($ports.allocated.$portStr -or $ports.reserved.$portStr) {
    Write-Host "[ERROR]  $Port " -ForegroundColor Red
    Write-Host " -Port  (3011-3019)" -ForegroundColor Red
    exit 1
}

$ports.allocated.$portStr = @{
    owner = $AgentName
    role = "agent-worktree"
    status = "active"
    worktree = $worktreePath
    branch = $branchName
    allocated_at = (Get-Date -Format "o")
}

$ports | ConvertTo-Json -Depth 5 | Set-Content -Path $portsFile -Encoding UTF8

# =====  =====
Write-Host "[5/6]  (,  npm install)" -ForegroundColor Cyan
Write-Host "  cd $worktreePath" -ForegroundColor Gray
Write-Host "  npm install" -ForegroundColor Gray

# =====  AGENT_GUIDELINES.md () =====
$guidelinesPath = Join-Path $parentDir "AGENT_GUIDELINES.md"
if (-not (Test-Path $guidelinesPath)) {
    Write-Host "  [WARN] AGENT_GUIDELINES.md , " -ForegroundColor Yellow
}

# =====  =====
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  [OK] AGENT BOOTSTRAP " -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Agent : $AgentName" -ForegroundColor White
Write-Host "  Worktree:   $worktreePath" -ForegroundColor White
Write-Host "  :       $branchName" -ForegroundColor White
Write-Host "  :   $Port" -ForegroundColor White
Write-Host "  :   $((3004 + ($Port - 3010)))" -ForegroundColor White
Write-Host "  :   .coord/ports.json" -ForegroundColor White
Write-Host "  Env :   $worktreePath\.env.agent" -ForegroundColor White
Write-Host ""
Write-Host "  :" -ForegroundColor Cyan
Write-Host "    cd $worktreePath" -ForegroundColor White
Write-Host "    npm install" -ForegroundColor White
Write-Host "    cp d:\filework\spec_template.md .\spec.md  # " -ForegroundColor White
Write-Host "    # " -ForegroundColor White
Write-Host ""
Write-Host "  :" -ForegroundColor Cyan
Write-Host "    python test.py --port $Port --single <test_path>" -ForegroundColor White
Write-Host "    : http://localhost:$((3004 + ($Port - 3010)))/" -ForegroundColor White
Write-Host ""
Write-Host "  :" -ForegroundColor Cyan
Write-Host "    cd $worktreePath" -ForegroundColor White
Write-Host "    git add . && git commit -m '...'" -ForegroundColor White
Write-Host "    #  merge" -ForegroundColor White
Write-Host ""