#!/usr/bin/env node
/**
 * generate_action_types.js
 *
 * 从后端 /api/v2/action/_openapi.json 自动生成 TypeScript 类型定义。
 * 输出: src/composables/useBoAction.types.d.ts
 *
 * 使用: node scripts/generate_action_types.js [http://localhost:3010]
 */
'use strict';

const fs = require('fs');
const path = require('path');
const http = require('http');

const BASE = process.argv[2] || process.env.BO_ACTION_BASE || 'http://localhost:3010';
const OUTPUT = path.join(__dirname, '..', 'src', 'composables', 'useBoAction.types.d.ts');

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    http.get(url, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(new Error(`Invalid JSON from ${url}: ${e.message}`)); }
      });
    }).on('error', reject);
  });
}

function schemaToTs(schema, depth = 0) {
  if (!schema) return 'any';
  if (depth > 5) return 'any'; // 防止循环
  if (schema.$ref) return schema.$ref.split('/').pop();
  if (schema.type === 'object' && schema.properties) {
    const props = Object.entries(schema.properties).map(([k, v]) => {
      const optional = schema.required && schema.required.includes(k) ? '' : '?';
      return `  ${k}${optional}: ${schemaToTs(v, depth + 1)};`;
    });
    return props.length ? `{\n${props.join('\n')}\n}` : 'Record<string, any>';
  }
  if (schema.type === 'array') {
    return `${schemaToTs(schema.items, depth + 1)}[]`;
  }
  if (schema.type === 'string' && schema.enum) {
    return schema.enum.map(v => `'${v}'`).join(' | ');
  }
  if (schema.type === 'string' && schema.format === 'date') return 'string';
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  return 'any';
}

function safeId(id) {
  return id.replace(/[^a-zA-Z0-9_]/g, '_');
}

function capitalize(s) {
  return s.split(/[._]/).map(p => p[0].toUpperCase() + p.slice(1)).join('');
}

async function main() {
  console.log(`[generate_action_types] Fetching OpenAPI from ${BASE}/api/v2/action/_openapi.json ...`);
  const spec = await fetchJson(`${BASE}/api/v2/action/_openapi.json`);

  const actions = [];
  for (const [pathKey, pathItem] of Object.entries(spec.paths || {})) {
    for (const [method, op] of Object.entries(pathItem)) {
      const actionId = op.operationId;
      if (!actionId) continue;

      const safeA = safeId(actionId);
      const inputSchema = spec.components?.schemas?.[`${safeA}_input`] || { type: 'object' };
      const outputSchema = spec.components?.schemas?.[`${safeA}_output`] || { type: 'object' };

      actions.push({
        id: actionId,
        safeId: safeA,
        name: capitalize(actionId),
        input: schemaToTs(inputSchema),
        output: schemaToTs(outputSchema),
        method: method.toUpperCase(),
        summary: op.summary || actionId,
        requiresAdmin: (op.description || '').includes('admin only'),
      });
    }
  }

  // 构造 .d.ts
  let ts = `// Auto-generated by scripts/generate_action_types.js\n`;
  ts += `// DO NOT EDIT MANUALLY\n`;
  ts += `// Date: ${new Date().toISOString()}\n\n`;

  ts += `export type ActionId = ${actions.map(a => `'${a.id}'`).join('\n  | ')};\n\n`;

  ts += `export interface ActionRegistry {\n`;
  for (const a of actions) {
    ts += `  '${a.id}': { input: ${a.input}; output: ${a.output}; };\n`;
  }
  ts += `}\n\n`;

  ts += `export interface BoActionResponse<T = any> {\n`;
  ts += `  success: boolean;\n`;
  ts += `  data: T;\n`;
  ts += `  message: string;\n`;
  ts += `}\n\n`;

  ts += `export declare function callPost<T extends ActionId>(\n`;
  ts += `  action_id: T,\n`;
  ts += `  params: ActionRegistry[T]['input']\n`;
  ts += `): Promise<BoActionResponse<ActionRegistry[T]['output']>>;\n\n`;

  ts += `export declare function callGet<T extends ActionId>(\n`;
  ts += `  action_id: T,\n`;
  ts += `  params?: ActionRegistry[T]['input']\n`;
  ts += `): Promise<BoActionResponse<ActionRegistry[T]['output']>>;\n\n`;

  ts += `export declare function callPut<T extends ActionId>(\n`;
  ts += `  action_id: T,\n`;
  ts += `  params: ActionRegistry[T]['input']\n`;
  ts += `): Promise<BoActionResponse<ActionRegistry[T]['output']>>;\n\n`;

  ts += `export declare function callDelete<T extends ActionId>(\n`;
  ts += `  action_id: T,\n`;
  ts += `  params: ActionRegistry[T]['input']\n`;
  ts += `): Promise<BoActionResponse<ActionRegistry[T]['output']>>;\n\n`;

  // 列出所有 Action 元数据 (调试/UI 文档)
  ts += `export const ACTIONS = [\n`;
  for (const a of actions) {
    ts += `  { id: '${a.id}', summary: ${JSON.stringify(a.summary)}, method: '${a.method}', requiresAdmin: ${a.requiresAdmin} },\n`;
  }
  ts += `] as const;\n`;

  fs.writeFileSync(OUTPUT, ts, 'utf-8');
  console.log(`[generate_action_types] Generated ${actions.length} action types to ${OUTPUT}`);
}

main().catch(e => {
  console.error(`[generate_action_types] FAILED: ${e.message}`);
  process.exit(1);
});
