content = open(r'd:\filework\release-prep-worktree\deploy_bundle\deploy.sh', 'rb').read()
print('本地 deploy.sh:')
print('  长度:', len(content))
print('  CRLF?', b'\r\n' in content)
print('  含 mv 逻辑?', b'mv "$DEPLOYMENTS_DIR/$item"' in content)
print('  含 VERSION_PATH 旧版 mv?', b'for item in meta frontend_dist_files MANIFEST telemetry mcp' in content)
print('  含 V007.21 cache_manager 检查?', b'async with self._lock' in content)
print('  含 busy_timeout 检查?', b'busy_timeout.*30000' in content)
print('  含 skip_audit 检查?', b'skip_audit=True' in content)
print('  含 self-repair lib/ CRLF?', b'lib/*.sh' in content)
print()
print('前 500 字符:')
print(content[:500].decode('utf-8', errors='replace'))
